global:
  scrape_interval:     5s
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'mosquitto-exporter-job'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mqtt-exporter:2112']



